export const ingredients = [
    { id: 1, name: "Tomato", unit: "kg" },
    { id: 2, name: "Garlic", unit: "g" },
    { id: 3, name: "Onion", unit: "kg" },
    { id: 4, name: "Potato", unit: "kg" },
    { id: 5, name: "Carrot", unit: "kg" },
    { id: 6, name: "Cucumber", unit: "units" },
    { id: 7, name: "Bell Pepper", unit: "units" },
    { id: 8, name: "Eggplant", unit: "kg" },
    { id: 9, name: "Zucchini", unit: "kg" },
    { id: 10, name: "Chicken Breast", unit: "kg" },
    { id: 11, name: "Beef", unit: "kg" },
    { id: 12, name: "Pork", unit: "kg" },
    { id: 13, name: "Bacon", unit: "g" },
    { id: 14, name: "Salmon", unit: "kg" },
    { id: 15, name: "Shrimp", unit: "g" },
    { id: 16, name: "Butter", unit: "g" },
    { id: 17, name: "Flour", unit: "g" },
    { id: 18, name: "Sugar", unit: "g" },
    { id: 19, name: "Salt", unit: "g" },
    { id: 20, name: "Black Pepper", unit: "g" },
    { id: 21, name: "Paprika", unit: "g" },
    { id: 22, name: "Basil", unit: "g" },
    { id: 23, name: "Oregano", unit: "g" },
    { id: 24, name: "Thyme", unit: "g" },
    { id: 25, name: "Rosemary", unit: "g" },
    { id: 26, name: "Parsley", unit: "g" },
    { id: 27, name: "Mint", unit: "g" },
    { id: 28, name: "Eggs", unit: "units" },
    { id: 29, name: "Milk", unit: "g" },
    { id: 31, name: "Minced meat", unit: "g" },
    { id: 32, name: "Hamburger buns", unit: "g" },
    { id: 33, name: "Lettuce", unit: "g" }
];
